repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      args:
      - --config=.flake8
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
      - --rcfile=.pylintrc
    - id: pydocstyle
      name: pydocstyle
      entry: pydocstyle
      language: system
      types: [python]
