dataset: summer2winter_yosemite

data_loader:
  name: GENERATOR
  crop: True
  before_crop_size: [286, 286]
  enable_normalization: True
  target_size: [256, 256, 3]


data_paths:
  extension: .jpg
  shuffle: True

paths:
  data:
    train_A: data/{{dataset}}/trainA
    train_B: data/{{dataset}}/trainB
    test_A: data/{{dataset}}/testA
    test_B: data/{{dataset}}/testB
  checkpoint: checkpoints/train
  tensorboard: tensorboard

model:
  input_dim: [256, 256, 3]
  learning_rate: 0.0002
  cycle_loss_lambda: 10.0
  enable_identity_loss: False
  gan_loss_criterion: mean_squared_error
  generated_images_buffer_size: 50

training:
  epochs: 500
  frequency_checkpoints: 1
  example_images_number_checkpoint: 5
  max_checkpoints: 5

logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  level: DEBUG